console.log('Snov Email-Click: Active');

/**
 * Converts visible email text nodes into clickable mailto launchers.
 *
 * The function scans the current document for elements matching the
 * `.long-email-width` selector, styles each unprocessed email entry as a
 * clickable control, and attaches a capturing click handler that opens the
 * user's default mail client via a `mailto:` URL.
 *
 * @returns {void} Does not return a value.
 *
 * @example
 * // After the DOM contains an element like:
 * // <span class="long-email-width">user@example.com</span>
 * hijackEmailText();
 * // Clicking the element navigates to: mailto:user@example.com
 */
function hijackEmailText() {
    const emailElements = document.querySelectorAll('.long-email-width');

    emailElements.forEach(emailEl => {
        if (!emailEl.dataset.hijacked) {
            const emailText = emailEl.innerText.trim();

            if (emailText && emailText.includes('@')) {
                emailEl.style.cursor = 'pointer';
                emailEl.style.color = '#6d53de';

                emailEl.setAttribute('title', `Написать письмо: ${emailText}`);

                /**
                 * Opens the default mail client for the selected email address.
                 *
                 * @param {MouseEvent} e The click event generated by the email element.
                 * @returns {void} Does not return a value.
                 *
                 * @example
                 * // Invoked automatically when the decorated email element is clicked.
                 * handleEmailClick(new MouseEvent('click'));
                 */
                function handleEmailClick(e) {
                    e.preventDefault();
                    e.stopPropagation();

                    console.log(`Email clicked -> Mailto: ${emailText}`);
                    window.location.href = `mailto:${emailText}`;
                }

                emailEl.addEventListener('click', handleEmailClick, true);

                emailEl.dataset.hijacked = 'true';
            }
        }
    });
}

let timeout;

/**
 * Re-applies email click behavior after DOM mutations settle.
 *
 * The observer callback debounces repeated mutations so the script avoids
 * reprocessing the page on every small DOM update.
 *
 * @returns {void} Does not return a value.
 *
 * @example
 * // When new matching nodes are inserted into the page,
 * // the callback schedules `hijackEmailText()` to run after 500 ms.
 * handleMutations();
 */
function handleMutations() {
    clearTimeout(timeout);
    timeout = setTimeout(hijackEmailText, 500);
}

const observer = new MutationObserver(handleMutations);

observer.observe(document.body, {
    childList: true,
    subtree: true
});

hijackEmailText();
